### ISSUE TITLE
TypescriptModelRenderer: Asterisks in descriptions break output

### ISSUE THREAD

**Issue by leonadler** [gentics/mesh-model-generator#10]
Added with 0.9.10, the output breaks due to special characters in descriptions:

Example for `GET /{projectName}/nodes`:
```yaml
description: Read all nodes and return a paged list response.
queryParameters: 
    role: 
        description: |
            The role permission parameter can be used to set the role parameter value in form of an UUID which will cause mesh to add the rolePerm field to the rest response.
            This may be useful when you are logged in as admin but you want to retrieve the editor role permissions on a given node.
            When used, the response will include the *rolePerms* property which lists the permissions for the specified role.
            Endpoint: */api/v1/:projectName/nodes?role=:roleUuid*
        type: string
        required: false
        repeat: false
        example: "24cf92691c7641158f92691c76c115ef"
```

TypeScript output:
```TypeScript
interface SomeRequestType {
    queryParams?: {
        /**
         * The role permission parameter can be used to set the role parameter value in form of an UUID which will cause mesh to add the rolePerm field to the rest response.
         * This may be useful when you are logged in as admin but you want to retrieve the editor role permissions on a given node.
         * When used, the response will include the *rolePerms* property which lists the permissions for the specified role.
         * Endpoint: */api/v1/:projectName/nodes?role=:roleUuid*
         */
        role?: string;
    };
}
```

The `*/` ends the doc comment and breaks the TypeScript output.
