### ISSUE TITLE
TypeScriptRenderer: All number parameters default to "NaN"

### ISSUE THREAD

**Issue by leonadler** [gentics/mesh-model-generator#11]
Example RAML:
```yaml
queryParameters: 
    cropx: 
        description: Set image crop area start x coordinate.
        type: number
        required: false
        repeat: false
        example: "260"
```

is rendered as:
```TypeScript
queryParams?: {
    /**
        * Set image crop area start x coordinate (default: NaN).
        * @example 260
        */
    cropx?: number;
```

Expected:
No `(default: ...)` text is output
