### ISSUE TITLE
TypescriptModelRenderer: Multiple examples are rendered as one long string

### ISSUE THREAD

**Issue by leonadler** [gentics/mesh-model-generator#5]
Only happens for `/roles/{roleUuid}/permissions/{pathToElement}` (GET, POST).

Input RAML:
```yaml
uriParameters: 
    pathToElement: 
        displayName: pathToElement
        description: API path to the element.
        type: string
        required: true
        repeat: false
        example: |
            projects/9b492ae687974f06892ae687978f060c
            projects/93494c1ff87d44f4894c1ff87da4f406/nodes/6f3ffb36e1324750bffb36e13277508a
```

Expected:
```typescript
urlParams: {
    /**
     * API path to the element.
     * @example
     *   "projects/650444b34688442c8444b34688742c05"
     *   "projects/b646913e642442d186913e6424f2d182/nodes/8e90debc1934482c90debc1934982cdd"
     */
    pathToElement: string;
};
```

Actual:
```typescript
urlParams: {
    /**
     * API path to the element.
     * @example "projects/650444b34688442c8444b34688742c05\nprojects/b646913e642442d186913e6424f2d182/nodes/8e90debc1934482c90debc1934982cdd\n"
     */
    pathToElement: string;
};
```
