### ISSUE TITLE
Parser & Renderer: Support `multipart/form-data` requests

### ISSUE THREAD

**Issue by leonadler** [gentics/mesh-model-generator#6]
The endpoint `POST /{project}/nodes/{nodeUuid}/binary/{fieldName}` accepts a `multipart/form-data` request body.

Example RAML:
```yaml
post:
    description: Update the binaryfield with the given name.
    body: 
        multipart/form-data: 
            formParameters: 
                binary: 
                    description: Single binary file part.
                    type: file
                    required: true
                    repeat: false
                language: 
                    description: Language of the node content which contains the binary field which should be updated.
                    type: string
                    required: true
                    repeat: false
                    example: en
                version: 
                    description: Version of the node which should be updated. This information is used to determine conflicting updates.
                    type: string
                    required: true
                    repeat: false
                    example: "1.0"
```

Could be rendered as:
```typescript
'/{project}/nodes/{nodeUuid}/binary/{fieldName}': {
    request: {
        ...
        body: {
            /** Single binary file part. */
            binary: File;
            /**
             * Language of the node content which contains the binary field which should be updated.
             * @example "en"
             */
            language: string;
            /**
             * Version of the node which should be updated. This information is used to determine
             * conflicting updates.
             * @example "1.0"
             */
            version: string;
        }
    };
    ...
};
```
